export const MAIN_ROUTE = '/'
export const SERVICE_ROUTE = '/service'
export const PRICES_ROUTE = '/prices'
export const EMPLOYEES_ROUTE = '/employees'
export const DOCUMENTS_ROUTE = '/documents'
export const SALE_ROUTE = '/sale'
export const CONTACTS_ROUTE = '/contacts'
export const CONTACTS_ABOUT_ROUTE = CONTACTS_ROUTE + '/about'
export const CONTACTS_DOCUMENTS_ROUTE = CONTACTS_ROUTE + '/documents'
export const CONTACTS_VACANCIES_ROUTE = CONTACTS_ROUTE + '/vacancies'

export const ADMIN_ROUTE = '/admin'
export const PROFILE_ROUTE = '/user'
export const BASKET_ROUTE = '/basket'
export const TEL_ROUTE = '/tel'
export const TEL_ROUTE_ADM = '/tel/adm'
export const CERT_ROUTE = '/cert'
export const KEYS_ROUTE = '/keys'

export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'

export const SHOP_ROUTE = '/shop'
export const SHOP_DEVICE_ROUTE = SHOP_ROUTE + '/device'
export const SHOP_ADMIN_ROUTE = SHOP_ROUTE + '/admin'